// VAL.PEA — mémoire des contre-expertises (06/10/2026).
// Chaque contre-expertise est datée : c'est une photo à l'instant T, jamais
// effacée. Celles faites avec Claude dans la conversation sont écrites ici ;
// celles du bouton « Contre-expertise IA » sont gardées dans le navigateur.
// concl : 'intacte' | 'fragilisee' | 'cassee'
const CE = {
AMS:[{date:'2026-10-06', concl:'fragilisee', point:'réservations (Air Distribution)',
  resume:"S1 2026 : CA +5,1 % à changes constants, porté par les logiciels compagnies (+8,7 %) et l'hôtellerie (+9,2 %) ; la réservation, près de la moitié du CA, ne fait que +1,1 %. Objectif 2026 abaissé à « moyen à haut à un chiffre » (Moyen-Orient, IATA à +2,1 %). Rentabilité intacte : marge d'EBIT ajustée 30,3 %, dette 1x EBITDA, rachat de 500 M€ terminé.",
  kpi:[["Réservations","−3,7 % au S1 (−7,6 % au T2)","ALERTE"],["Objectif 2026","abaissé en juillet","ALERTE"],["Marge d'EBIT ajustée","30,3 % (+0,5 pt)","OK"]],
  direction:"Luis Maroto, PDG depuis 2011 ; pas de changement ni de conflit trouvé ; ventes d'actions des dirigeants : non trouvé.",
  analystes:"Deutsche Bank passe à l'achat le 16/09/2026, objectif 58 → 71,50 € (effet de l'IA estimé à −5 % sur le BPA 2028).",
  contre:"La réservation stagne, peut-être durablement (vente directe des compagnies, agents IA). La croissance retenue (7,5 %) était trop haute : le semestre réel fait 5,1 % → ramenée à 5,5 %.",
  decision:"Pas d'achat d'un bloc : au mieux une demi-position en bas de zone, puis attendre le CA du 3e trimestre.",
  sources:[["Amadeus – communiqué S1 2026","https://amadeus.com/content/dam/amadeus/corporate/documents/en/investors/2026/results/h1/h1-2026-results-press-release.pdf"],["Finimize – objectif 2026 abaissé","https://finimize.com/content/amadeus-trims-2026-outlook-as-middle-east-cancellations-rise"],["Deutsche Bank à l'achat","https://www.ad-hoc-news.de/boerse/news/corporate-news/deutsche-bank-upgrades-amadeus-it-stock-to-buy-at-eur-71-50/70211345"]],
  by:'Claude (conversation)'}],
RMS:[{date:'2026-10-06', concl:'fragilisee', point:'Asie / Chine', resume:"S1 2026 : CA 8,2 Md€, +6 % à changes constants (T1 +6 %, T2 +7 %). Amériques +15 %, Japon +11 %, maroquinerie +10 %, mais Asie hors Japon +2 % et parfums −4 %. Marge opérationnelle courante 41,0 % (41,4 % un an plus tôt). Pas d'objectif chiffré. Cours au plus bas depuis 2022 fin septembre.",
 kpi:[["Croissance à changes constants","+6 % (S1 2026)","OK"],["Marge opérationnelle courante","41,0 % contre 41,4 %","ALERTE"],["Asie hors Japon","+2 % (S1 2026)","ALERTE"]],
 direction:"Aucun changement. Achats massifs de la famille Dumas (env. 30 M€ entre mai et septembre), aucune vente.",
 analystes:"Baisses d'objectifs en série : RBC 1600 €, Oddo 1470 €, JPMorgan 1600 €, Citi 1540 €, Rothschild Redburn passe à Neutre (1410 €, 01/10), Bernstein reste à l'achat (1750 €).",
 contre:"Même après la chute, Hermès vaut environ 33 fois ses bénéfices 2027 contre 18 pour LVMH : aucune marge d'erreur si l'Asie ne repart pas.",
 decision:"Garder (moat intact, famille acheteuse), ne pas renforcer : ligne trop grosse et cours loin de la zone.",
 sources:[["Journal du Luxe – S1 2026","https://www.journalduluxe.fr/fr/business/hermes-chiffres-financiers-premier-semestre-2026"],["Option Finance – analystes 01/10","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-10-01-hermes-toujours-pris-dans-le-feu-croise-des-analystes.html"],["ABC Bourse – transactions dirigeants","https://www.abcbourse.com/marches/transactions_dirigeants/FR0000052292p"]], by:'Claude (conversation)'}],
EL:[{date:'2026-10-06', concl:'intacte', point:'activité · vigilance gouvernance', resume:"S1 2026 : CA 14,8 Md€, +9,7 % à changes constants (T2 +8,7 %, ralentissement), marge opérationnelle ajustée 18,6 % (+50 pb). Les lunettes IA ont presque doublé au T2. Correction : la « baisse des marges » citée en février ne s'est pas confirmée.",
 kpi:[["Croissance à changes constants","+9,7 % S1 (T2 +8,7 %)","OK"],["Marge opérationnelle ajustée","18,6 % (+50 pb)","OK"],["Gouvernance","conflit Del Vecchio / Milleri","ALERTE"]],
 direction:"25/08 : Leonardo Maria Del Vecchio quitte ses fonctions et critique le PDG ; 09/09 : le conseil confirme Milleri à l'unanimité. Succession Delfin (32,4 %) non réglée. Delfin a acheté pour env. 37 M€ (juin-août).",
 analystes:"Objectifs en baisse : Goldman Neutre 165 €, Bernstein 185 €, BofA 237 €, Jefferies Achat 250 €, Stifel Achat 280 € (prévoit un ralentissement vers +5 %).",
 contre:"Gouvernance : l'actionnaire de contrôle est bloqué par une succession et un héritier attaque publiquement le PDG ; la croissance ralentirait vers 5 % au S2 selon Stifel.",
 decision:"Activité solide mais valeur hors filtre qualité (ROIC) : garder petit, ne pas renforcer, revoir aux résultats annuels.",
 sources:[["EssilorLuxottica S1 2026","https://www.biospace.com/press-releases/essilorluxottica-q2-h1-2026-results-solid-revenue-trajectory-at-9-7-in-h1-with-q2-at-8-7-increasing-profitability-with-adj-operating-profit-15"],["Modaes – démission du fils du fondateur","https://www.modaes.com/global/companies/the-son-of-essilorluxotticas-founder-resigns-from-his-positions-following-a-dispute-with-the-ceo"],["Option Finance – analystes 25/09","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-09-25-essilorluxottica-recule-les-analystes-rabotent-toujours-leurs-objectifs.html"]], by:'Claude (conversation)'}],
INTERPARFUMS:[{date:'2026-10-06', concl:'fragilisee', point:'croissance négative, dépendance aux licences', resume:"S1 2026 : CA 414,3 M€, −3,7 % à devises constantes ; marge opérationnelle 21,1 % (23,2 %), aidée par un remboursement de droits de douane. Objectif 2026 : 850-870 M€ (890 M€ en 2025). Bonne nouvelle : licence Puma gagnée jusqu'en 2037 (lancement 2027).",
 kpi:[["CA à devises constantes","−3,7 % (S1 2026)","ALERTE"],["Marge opérationnelle","21,1 % contre 23,2 %","ALERTE"],["Licences","Puma gagnée, aucune perdue","OK"]],
 direction:"Pas de changement. La maison mère américaine a acheté env. 36 M€ d'actions (août-septembre) : spéculations de rachat total.",
 analystes:"Oddo passe à Surperformance (32 €), TP ICAP Conserver (30 €), Goldman Achat (34 €).",
 contre:"Les marques ne lui appartiennent pas : TP ICAP justifie une décote durable par le risque de reprise des licences, et la croissance 2026 est négative.",
 decision:"Hors filtre qualité : sortie selon la règle, sauf si tu la gardes comme poche tendance avec une sortie écrite à l'avance.",
 sources:[["Option Finance – S1 23/07","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-07-23-interparfums-fait-moins-bien-que-prevu-au-1er-semestre-et-decroche-en-bourse.html"],["FashionNetwork – licence Puma","https://fr.fashionnetwork.com/news/Puma-confie-ses-parfums-a-interparfums,1869135.html"],["Option Finance – TP ICAP 31/08","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-08-31-tp-icap-midcap-releve-son-objectif-sur-interparfums.html"]], by:'Claude (conversation)'}],
SU:[{date:'2026-10-06', concl:'fragilisee', point:'bilan et prix payé pour PTC', resume:"S1 2026 record : croissance organique +14 %, marge EBITA ajustée 19,3 % (+120 pb), objectif 2026 relevé à +10-13 %. Mais deux achats de logiciels chers en 3 mois : Cognite (3,1 Md$, 01/07) puis PTC (22,6 Md$ en cash, 05/10), financés par 16-17 Md€ de dette et 5-6 Md€ d'actions nouvelles.",
 kpi:[["Croissance organique","+14 % (S1 2026)","OK"],["Marge EBITA ajustée","19,3 % (+120 pb)","OK"],["Dette / EBITDA après PTC","~3x (presse, non publié)","ALERTE"]],
 direction:"Olivier Blum porte l'opération ; pas de conflit trouvé.",
 analystes:"Réactions mitigées le 05/10 : Jefferies et JPMorgan défendent la logique stratégique ; RBC et AlphaValue s'inquiètent du bilan « tendu à l'extrême ». Pas de changement de recommandation daté.",
 contre:"PTC payé environ 20 fois l'EBITDA 2027, levier proche de 3x et dilution, sur un logiciel exposé aux craintes liées à l'IA.",
 decision:"Le métier de base est excellent : garder, ne rien faire avant les résultats annuels de février (dette, financement, synergies).",
 sources:[["Option Finance – S1 record","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-07-30-schneider-electric-releve-ses-objectifs-apres-un-premier-semestre-record.html"],["Financier Worldwide – PTC","https://www.financierworldwide.com/fw-news/2026/10/6/schneider-electric-strikes-226bn-ptc-deal"],["Il Sole 24 Ore – levier","https://en.ilsole24ore.com/art/in-paris-schneider-electric-acquires-ptc-for-226-billion-AJt7tUZB"]], by:'Claude (conversation)'}],
LR:[{date:'2026-10-06', concl:'intacte', point:'sous surveillance data centers', resume:"S1 2026 : croissance organique +9,8 %, objectif 2026 relevé à +8-10 %. Le 28/09, objectifs 2027-2030 relevés : +6-8 %/an organique (contre 3-5 %) et marge 21-22 %.",
 kpi:[["Croissance organique","+9,8 % (S1 2026)","OK"],["Part des data centers","32 % du CA, +30 %","OK"],["Marge opérationnelle ajustée","20,8 % contre 21,0 %","ALERTE"]],
 direction:"Benoît Coquart reste DG ; pas de conflit.",
 analystes:"RBC passe à Surperformance (160 €, 03/08) ; Jefferies 168 €, Deutsche Bank Achat 160 €.",
 contre:"Un tiers du CA dépend des investissements dans les data centers d'IA, alors que la marge recule légèrement et que la dette a augmenté de 75 % en un an.",
 decision:"Garder ; trop chère pour renforcer.",
 sources:[["Business Wire – S1 2026","https://www.businesswire.com/news/home/20260728474035/en/"],["Option Finance – objectifs relevés","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-09-28-legrand-releve-ses-ambitions-grace-a-la-croissance-des-centres-de-donnees.html"]], by:'Claude (conversation)'}],
HO:[{date:'2026-10-06', concl:'intacte', point:'cyber à surveiller', resume:"S1 2026 : commandes record 12,47 Md€ (+21 %), CA 10,95 Md€ (+7,8 % organique), marge EBIT ajustée 12,5 % (+30 pb) ; charge de 450 M€ (annulation des frégates allemandes F126). Objectifs 2026 confirmés. Correction : les +9,7 % et +27 % cités avant étaient ceux du 1er trimestre.",
 kpi:[["Croissance organique","+7,8 % (S1 2026)","OK"],["Commandes / CA","~1,14","OK"],["Cybersécurité","+1,6 % au S1 après 4 trimestres négatifs","ALERTE"]],
 direction:"Patrice Caine reconduit jusqu'en 2030 ; nouveau directeur financier (ex-Nissan) le 01/07.",
 analystes:"Oddo 305 €, Jefferies 290 €, Bernstein 290 €, Berenberg Conserver 265 € (23/07). JPMorgan Neutre depuis mars.",
 contre:"Selon JPMorgan, la faiblesse de la cybersécurité est structurelle et explique la décote face aux autres groupes de défense.",
 decision:"Garder ; trop chère pour renforcer.",
 sources:[["Option Finance – S1 23/07","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-07-23-prises-de-commandes-en-nette-hausse-pour-thales.html"],["Option Finance – analystes","https://www.optionfinance.fr/info-financiere-en-continu/d/2026-07-23-thales-en-hausse-apres-ses-resultats-lavis-des-analystes.html"]], by:'Claude (conversation)'}],
AI:[{date:'2026-10-06', concl:'intacte', point:'croissance qui plafonne', resume:"S1 2026 : ventes comparables +2,6 % (T2 +3,5 %), marge +110 pb, objectif de marge 2027 en bonne voie. Cash-flow libre du semestre à zéro (besoin en fonds de roulement) et dette passée de 8,4 à 13,9 Md€ avec le rachat de DIG Airgas.",
 kpi:[["Ventes comparables","+2,6 % (S1 2026)","OK"],["Marge opérationnelle","20,9 % (+100 pb)","OK"],["Cash-flow libre S1","~0 € (fonds de roulement)","ALERTE"]],
 direction:"Benoît Potier et François Jackow reconduits pour 4 ans (AG du 05/05).",
 analystes:"Jefferies Achat 204 €, Oddo 216 € (28/07) ; Morgan Stanley prudent sur la croissance.",
 contre:"Un carnet record de 6 Md€ ne produit toujours pas d'accélération des ventes : la valorisation repose presque uniquement sur la hausse des marges.",
 decision:"Exception « bon père de famille » maintenue ; ne pas renforcer (ligne > 10 %).",
 sources:[["Air Liquide – S1 2026","https://www.airliquide.com/group/press-releases-news/2026-07-28/h1-2026-results-acceleration-second-quarter-air-liquide-combines-growth-continuous-performance"],["Investing – cash-flow faible","https://www.investing.com/news/earnings/air-liquide-q2-sales-beat-on-electronics-demand-keeps-margin-goals-4815501"]], by:'Claude (conversation)'}],
ASML:[{date:'2026-10-06', concl:'intacte', point:'valorisation', resume:"T2 2026 : CA 9,3 Md€, marge brute 54 %. Objectif 2026 relevé deux fois : 43-45 Md€ (36-40 auparavant). Capacités EUV +30 % prévues en 2027. Part de la Chine ramenée vers 20 %. ASML ne publie plus ses commandes depuis 2026.",
 kpi:[["Commandes","plus publiées depuis 2026","NON VÉRIFIABLE"],["Marge brute","54 % (T2), 55-57 % visé au T3","OK"],["Objectif 2026","43-45 Md€, relevé","OK"]],
 direction:"Christophe Fouquet PDG ; 1 700 suppressions de postes annoncées en janvier.",
 analystes:"Hausses d'objectifs en juillet : Bernstein, RBC, JPMorgan ; UBS Achat 2350 €.",
 contre:"Le cours suppose déjà une forte croissance en 2027, la fin de la publication des commandes réduit la visibilité, et de nouveaux projets américains visent les exportations vers la Chine.",
 decision:"Garder ; ne jamais vendre sur le prix seul ; ne pas renforcer (ligne à 10 %).",
 sources:[["ASML – investisseurs","https://www.asml.com/en/investors"],["Caixin – ventes en Chine","https://www.caixinglobal.com/2026-04-16/asmls-china-sales-slump-as-export-curbs-bite-102434749.html"]], by:'Claude (conversation)'}],
GTT:[{date:'2026-10-06', concl:'intacte', point:'carnet 2029+ à reconstituer', resume:"S1 2026 : CA 387,3 M€, résultat net 210,4 M€ (+16,9 %), carnet record 1 853 M€ (306 unités), objectifs 2026 confirmés. Au moins 62 méthaniers commandés depuis janvier. GTT prévoit ~550 méthaniers commandés entre 2026 et 2035.",
 kpi:[["Méthaniers commandés en 2026","≥ 62 à fin septembre","OK"],["Carnet de commandes","1 853 M€ (juin 2026)","OK"],["Marge d'EBITDA","68,1 % (S1 2026)","OK"]],
 direction:"François Michel directeur général ; pas de conflit.",
 analystes:"Berenberg passe à l'Achat, objectif 190 → 245 € (04/09).",
 contre:"Le carnet s'amenuise après 2028 (295 M€ pour 2029 et au-delà) et la Corée pousse ses propres cuves (méthanier Samsung KC-2C en service depuis fin 2025).",
 decision:"Thèse intacte : achat possible seulement en zone (≤ 209 €).",
 sources:[["GTT – résultats S1 2026","https://mfn.se/all/a/gaztransport-et-technigaz/gtt-resultats-du-1er-semestre-2026-carnet-de-commandes-a-un-niveau-historiquement-eleve-4d6eddd4"],["Berenberg à l'achat","https://www.boursedirect.fr/fr/actualites/categorie/commentaires-sur-l-evolution-des-valeurs-en-cours-de-seance/gtt-propulse-par-un-relevement-a-l-achat-chez-berenberg-zone-bourse-6f86d013ed00cc43fa1b52ceca6cb0d66f8d729c"]], by:'Claude (conversation)'}],
ELIS:[{date:'2026-10-06', concl:'intacte', point:'croissance à la limite', resume:"S1 2026 : CA 2,46 Md€, +3,2 % organique ; objectif 2026 confirmé (croissance légèrement inférieure à 3,8 %). Perte d'un gros contrat de santé publique au Mexique. Rachat d'actions de 500 M€ terminé ; levier 2,09x.",
 kpi:[["Croissance organique","+3,2 % (S1 2026)","OK (limite)"],["Marge d'EBITDA","34,7 %, stable","OK"]],
 direction:"Xavier Martiré président du directoire ; pas de conflit.",
 analystes:"RBC passe à Surperformance (28 €), Oddo 31,5 €, Jefferies 32 €.",
 contre:"Croissance faible dans les grands pays (France +2 %), rachat d'actions payé au-dessus du cours actuel, dette en hausse.",
 decision:"Entreprise solide mais hors filtre qualité (ROIC 5,7 %) : sortie selon la règle.",
 sources:[["Elis – S1 2026","https://www.globenewswire.com/news-release/2026/07/29/3335442/0/en/Elis-H1-2026-results.html"],["RBC à Surperformance","https://www.abcbourse.com/marches/elis-releve-a-surperformance-par-rbc-l-objectif-porte-a-28-euros_700894"]], by:'Claude (conversation)'}],
TTE:[{date:'2026-10-06', concl:'fragilisee', point:"rachats d'actions", resume:"T2 2026 : résultat net ajusté 6,0 Md$, porté par un Brent à ~104 $ (conflit au Moyen-Orient). Production −4 % sur un an. Dividende en hausse (acompte 0,90 €, +5,9 %) mais rachats réduits : 2 Md$ par trimestre en 2025, 0,75 Md$ au T1, 1,5 Md$ aux T2-T3.",
 kpi:[["Dividende","acompte 0,90 € (+5,9 %)","OK"],["Rachats d'actions","1,5 Md$/trim. contre 2 en 2025","ALERTE"],["Endettement (gearing)","13,1 %","OK"]],
 direction:"Patrick Pouyanné PDG ; pas de conflit.",
 analystes:"Morgan Stanley passe à Neutre (valorisation), 03/09.",
 contre:"Les résultats sont gonflés par une crise ; quand le pétrole baisse, les rachats sont la première variable d'ajustement.",
 decision:"Poche cyclique : garder pour le dividende, avec un stop écrit (proposé 68 €).",
 sources:[["TotalEnergies – T2 2026","https://totalenergies.com/system/files/documents/totalenergies_pr-results-2q26_2026_en.pdf"],["Rigzone – coupe des rachats","https://www.rigzone.com/news/wire/totalenergies_cuts_buyback_to_lower_end_of_range-11-feb-2026-182966-article/"]], by:'Claude (conversation)'}],
};
