// VAL.PEA — contenu qualitatif des fiches (05/10/2026).
// BROUILLONS rédigés par Claude, À VALIDER PAR VAL. Ce fichier n'est jamais
// modifié par le calcul automatique : c'est le seul endroit à éditer à la main.
//   why  : pourquoi posséder l'action (1 phrase)
//   wrong: ce qui prouverait que la thèse est fausse
//   comp : principaux concurrents [nom, commentaire]
//   kpi  : tableau de bord [indicateur, dernière valeur, alerte si…]
//   dep  : dépendance principale
//   next : prochain rendez-vous
// Deux alertes du tableau de bord en même temps = thèse cassée = vente.
const FICHE = {
GTT:{why:"Péage technologique sur le transport mondial de GNL : très peu de capital, marge d'EBITDA de 67 %, 80 % du bénéfice reversé.",
 wrong:"Les commandes de méthaniers s'effondrent durablement, une technologie concurrente perce, ou la redevance baisse.",
 comp:[["KC-1 (Corée)","2 premiers navires défectueux, quasi jamais exploités"],["Cuves Moss","technologie ancienne, moins de volume utile"],["Chantiers chinois","développent leurs propres systèmes : la menace à suivre"]],
 kpi:[["Méthaniers commandés","56 au S1 2026 (37 en 2025)","< 30 par an, 2 ans de suite"],["Carnet de commandes","1 853 M€ (juin 2026)","en baisse 2 semestres de suite"],["Marge d'EBITDA","68,1 % (S1 2026)","< 60 %"],["Dividende / action","8,94 € (2025)","en baisse"]],
 dep:"Constructions neuves : 92 % du chiffre d'affaires 2025", next:"CA du 3e trimestre : 23/10/2026"},
RMS:{why:"La maison de luxe la plus désirable du monde : rareté organisée, prix en hausse chaque année, aucune dette.",
 wrong:"La croissance passe sous 5 % deux semestres de suite, ou la marque baisse ses prix / multiplie les promotions.",
 comp:[["LVMH (Louis Vuitton)","plus gros, plus exposé à la mode"],["Chanel","non coté, même clientèle"],["Richemont","joaillerie et montres"]],
 kpi:[["Croissance à changes constants","+6 % (S1 2026)","< 5 % deux semestres de suite"],["Marge opérationnelle","—","< 38 %"],["Chine / Asie","—","recul 2 semestres de suite"]],
 dep:"Maroquinerie (sacs) : plus de 40 % des ventes", next:"CA du 3e trimestre"},
AI:{why:"Infrastructure invisible de l'industrie : contrats de 15 à 20 ans, prix indexés, dividende relevé depuis plus de 25 ans.",
 wrong:"La marge cesse de progresser (objectif 2027 abandonné) ou le dividende cesse d'augmenter.",
 comp:[["Linde","leader mondial, plus rentable"],["Air Products","n°3, plus endetté"],["Nippon Sanso","acteur asiatique"]],
 kpi:[["Ventes comparables","+2,6 % (S1 2026)","< 0 % sur un an"],["Marge opérationnelle","20,9 % (S1 2026)","objectif 2027 abandonné"],["Dividende","—","en baisse"]],
 dep:"Industrie et santé ; électronique en croissance", next:"CA du 3e trimestre"},
SU:{why:"Leader mondial de la gestion de l'électricité : data centers, électrification, logiciels industriels.",
 wrong:"Le rachat de PTC (22,6 Md$ en cash) fait chuter la rentabilité ou la dette dépasse 2,5 fois l'EBITDA durablement.",
 comp:[["ABB","concurrent direct, Suisse"],["Siemens","automatisation, Allemagne"],["Eaton","data centers, États-Unis"]],
 kpi:[["Croissance organique","+9 % (2025)","< 5 % sur un an"],["Dette / EBITDA après PTC","—","> 2,5"],["Marge d'EBITA ajustée","—","en baisse 2 ans de suite"]],
 dep:"Data centers et bâtiment", next:"Résultats annuels : février 2027 (point PTC)"},
ASML:{why:"Monopole mondial des machines de gravure EUV : sans elle, pas de puces avancées.",
 wrong:"Restrictions export qui coupent durablement la Chine et les autres clients, ou une technologie de gravure alternative crédible.",
 comp:[["Canon / Nikon","seulement sur les technologies anciennes (DUV)"],["Aucun en EUV","monopole de fait"]],
 kpi:[["Commandes (bookings)","—","en baisse 2 trimestres de suite"],["Marge brute","—","< 50 %"],["Part de la Chine","—","restriction majeure"]],
 dep:"TSMC, Samsung, Intel : quelques clients géants", next:"Résultats du 3e trimestre : mi-octobre"},
LR:{why:"Spécialiste mondial des équipements électriques du bâtiment, tiré par les data centers ; nombreuses acquisitions réussies.",
 wrong:"Les data centers ralentissent et la croissance organique repasse sous 3 %.",
 comp:[["Schneider Electric","plus grand, plus logiciel"],["ABB","électrification"],["Hager","non coté"]],
 kpi:[["Croissance organique","+7,7 % (2025)","< 3 % sur un an"],["Part des data centers","—","en recul"],["Marge opérationnelle","—","< 20 %"]],
 dep:"Bâtiment résidentiel et tertiaire, data centers", next:"CA du 3e trimestre"},
HO:{why:"Électronique de défense européenne : contrats longs, carnet de commandes record, budgets militaires en hausse.",
 wrong:"Les budgets de défense européens se retournent ou la cybersécurité continue de reculer.",
 comp:[["Leonardo","Italie"],["Rheinmetall","Allemagne, munitions et blindés"],["Hensoldt","capteurs, Allemagne"]],
 kpi:[["Croissance organique","+9,7 % (S1 2026)","< 5 %"],["Prises de commandes","+27 % (S1 2026)","ratio commandes/CA < 1"],["Cyber & Digital","en recul (S1 2026)","recul 2 semestres de suite"]],
 dep:"Défense : environ la moitié du CA", next:"CA du 3e trimestre"},
EL:{why:"Leader mondial des verres correcteurs et des montures (Ray-Ban), partenaire de Meta sur les lunettes connectées.",
 wrong:"Les lunettes IA d'Apple/Google/Samsung prennent la place de Ray-Ban Meta, ou les marges continuent de baisser.",
 comp:[["Hoya / Zeiss","verres"],["Apple, Google, Samsung","lunettes connectées"],["Warby Parker","distribution en ligne"]],
 kpi:[["Croissance à changes constants","> 10 % (3 derniers trimestres)","< 5 %"],["Marge opérationnelle","en baisse","nouvelle baisse"],["Piotroski","4/9","reste ≤ 4 en février"]],
 dep:"Verres et montures ; gouvernance contestée (sept. 2026)", next:"CA du 3e trimestre"},
ELIS:{why:"Leader européen de la location-entretien de linge et vêtements de travail : revenus récurrents, contrats de long terme.",
 wrong:"— Hors filtre qualité (ROIC 5,7 %) : pas de thèse qualité possible tant que la rentabilité du capital ne remonte pas.",
 comp:[["Cintas","États-Unis, plus rentable"],["Initial (Rentokil)","Royaume-Uni"],["Acteurs locaux","marché fragmenté"]],
 kpi:[["Croissance organique","+3,2 % (S1 2026)","< 3 %"],["Marge d'EBITDA","34,7 % (S1 2026)","< 33 %"]],
 dep:"Santé, hôtellerie-restauration, industrie", next:"CA du 3e trimestre"},
INTERPARFUMS:{why:"Exploitant de licences de parfums (Jimmy Choo, Coach, Montblanc) avec peu de dette.",
 wrong:"— Hors filtre qualité : ventes en recul, cash faible. Moat étroit : les marques ne lui appartiennent pas.",
 comp:[["Coty","licences, plus endetté"],["Puig","Espagne"],["L'Oréal Luxe","propriétaire de ses marques"]],
 kpi:[["Croissance à changes constants","−3,7 % (S1 2026)","objectif 2027 négatif"],["Marge opérationnelle","21,1 % (S1 2026)","< 20 %"],["Licences","—","perte d'une licence majeure"]],
 dep:"Jimmy Choo 25 %, Coach 22 %, Montblanc 21,5 % des ventes", next:"CA du 3e trimestre"},
TTE:{why:"Exception écrite (poche cyclique) : protection partielle contre l'inflation, dividende élevé.",
 wrong:"Le dividende est réduit, ou le cours clôture sous le stop fixé.",
 comp:[["Shell","Royaume-Uni"],["BP","Royaume-Uni"],["Eni","Italie"]],
 kpi:[["Cours vs stop","—","clôture sous 68 €"],["Dividende","en hausse","réduit"]],
 dep:"Prix du pétrole et du gaz", next:"Résultats du 3e trimestre : fin octobre"},
AMS:{why:"Réservation aérienne mondiale en quasi-duopole et logiciels de compagnies aériennes et d'aéroports.",
 wrong:"Les compagnies vendent massivement en direct (NDC) ou des agents IA contournent les plateformes de réservation.",
 comp:[["Sabre","n°2, endetté"],["Travelport","n°3, non coté"],["Vente directe NDC","la vraie menace"]],
 kpi:[["Réservations","−7,6 % (T2 2026)","recul sur 4 trimestres glissants"],["Objectif 2026","abaissé (1 chiffre moyen-haut)","nouvelle baisse"],["Marge","—","en baisse 2 ans de suite"]],
 dep:"Trafic aérien mondial", next:"Résultats du 3e trimestre"},
UMG:{why:"Premier catalogue musical mondial, oligopole de 3 majors, revenus récurrents du streaming.",
 wrong:"La musique générée par IA réduit la valeur des catalogues ou les plateformes imposent une baisse des redevances.",
 comp:[["Sony Music","n°2"],["Warner Music","n°3"],["Musique IA","menace nouvelle"]],
 kpi:[["Croissance à changes constants","+8,7 % (2025)","< 5 %"],["Abonnements streaming","+8,6 % (2025)","< 5 %"]],
 dep:"Spotify, Apple, Amazon, YouTube", next:"Résultats du 3e trimestre"},
WKL:{why:"Information professionnelle intégrée aux logiciels des fiscalistes, juristes et soignants : revenus récurrents.",
 wrong:"L'IA générative rend ses contenus banals et la croissance organique passe sous 4 %.",
 comp:[["Thomson Reuters","n°1 mondial"],["RELX (LexisNexis)","Royaume-Uni"],["Outils d'IA","menace nouvelle"]],
 kpi:[["Croissance organique","~6 % (2025)","< 4 %"],["Revenus récurrents","—","< 80 % du CA"]],
 dep:"Santé, fiscalité, juridique", next:"Résultats annuels : février"},
OR:{why:"Numéro un mondial de la beauté : 37 marques, R&D sans équivalent, distribution partout.",
 wrong:"La croissance à périmètre comparable passe sous 3 % deux ans de suite.",
 comp:[["Estée Lauder","en difficulté"],["Procter & Gamble","grande consommation"],["Marques indépendantes","digitales, rapides"]],
 kpi:[["Ventes comparables","+4 % (2025)","< 3 % deux ans de suite"],["Chine","—","recul durable"]],
 dep:"Luxe et dermatologie", next:"CA du 3e trimestre"},
SAF:{why:"Moteurs d'avions moyen-courriers (CFM avec GE) : les pièces de rechange rapportent pendant 30 ans.",
 wrong:"Défaut de qualité majeur sur le moteur LEAP ou baisse durable du trafic aérien.",
 comp:[["Pratt & Whitney","n°2 sur moyen-courrier"],["Rolls-Royce","long-courrier"]],
 kpi:[["CA ajusté","+15 % (2025)","< 8 %"],["Livraisons LEAP","—","en baisse"]],
 dep:"Airbus A320 et Boeing 737", next:"CA du 3e trimestre"},
AIR:{why:"Duopole mondial des avions de ligne avec Boeing, carnet de commandes de plus de 10 ans.",
 wrong:"Les livraisons stagnent durablement (chaîne d'approvisionnement) ou l'avion chinois COMAC perce.",
 comp:[["Boeing","n°2, affaibli"],["COMAC","Chine, à surveiller"]],
 kpi:[["Livraisons","objectif ~870 en 2026","objectif abaissé"],["Marge","—","en baisse"]],
 dep:"Aviation commerciale", next:"CA du 3e trimestre"},
DSY:{why:"Logiciels de conception 3D de l'industrie (CATIA, SolidWorks) : clients captifs pendant des décennies.",
 wrong:"La croissance reste sous 4 % (transition vers le cloud et l'IA ratée).",
 comp:[["Siemens","logiciels industriels"],["PTC","racheté par Schneider"],["Autodesk","États-Unis"]],
 kpi:[["Croissance à changes constants","+4 % (2025)","< 3 %"],["Abonnements","—","en recul"]],
 dep:"Industrie, santé (Medidata)", next:"CA du 3e trimestre"},
IPSEN:{why:"Laboratoire de médicaments de spécialité (oncologie, maladies rares) en croissance, peu endetté.",
 wrong:"Échecs de R&D ou arrivée des génériques sans relais : croissance < 5 %.",
 comp:[["Novartis, Pfizer, AstraZeneca","oncologie"],["Biotechs","maladies rares"]],
 kpi:[["Croissance à changes constants","+10,9 % (2025)","< 5 %"],["Pipeline","—","échec majeur en phase 3"]],
 dep:"Quelques médicaments phares", next:"CA du 3e trimestre"},
NRO:{why:"Société de services informatiques bien gérée, sans dette, croissance régulière.",
 wrong:"L'IA réduit les jours facturés et la croissance organique passe sous 2 %.",
 comp:[["Capgemini, Sopra Steria","plus gros"],["Wavestone","conseil, en difficulté"]],
 kpi:[["Croissance organique","+5,1 % (2025)","< 2 %"],["Taux d'occupation","—","en baisse"]],
 dep:"Grands comptes français", next:"CA du 3e trimestre"},
PLNW:{why:"Logiciel de gestion de portefeuilles de projets : abonnements, clients difficiles à faire partir.",
 wrong:"La croissance passe sous 7 % ou un géant (Microsoft, Oracle, SAP) l'écrase.",
 comp:[["Microsoft Project","dominant"],["Oracle, SAP","suites intégrées"]],
 kpi:[["Croissance à changes constants","+10,3 % (2025)","< 7 %"]],
 dep:"Petite taille", next:"Résultats semestriels / annuels"},
ITX:{why:"Zara : chaîne d'approvisionnement la plus rapide de la mode, très rentable, sans dette.",
 wrong:"La mode ultra-rapide (Shein) prend ses clients : croissance < 4 % deux ans de suite.",
 comp:[["H&M","moins rentable"],["Shein, Temu","ultra-rapide, bas prix"],["Uniqlo","Japon"]],
 kpi:[["Ventes à changes constants","+7 % (exercice 2025)","< 4 %"],["Marge brute","—","en baisse"]],
 dep:"Europe et mode féminine", next:"Résultats du 3e trimestre : décembre"},
RAA:{why:"Leader mondial des fours mixtes professionnels (environ 50 % du marché), très rentable.",
 wrong:"La restauration ralentit durablement et un concurrent asiatique casse les prix.",
 comp:[["Unox","Italie"],["Electrolux Professional","Suède"]],
 kpi:[["Croissance hors change","+8 % (2025)","< 3 %"]],
 dep:"Restauration professionnelle", next:"CA du 3e trimestre"},
NEM:{why:"Logiciels de conception pour le bâtiment (BIM) : clients captifs, passage aux abonnements.",
 wrong:"La croissance organique passe sous 8 % ou Autodesk gagne du terrain.",
 comp:[["Autodesk","n°1 mondial"],["Bentley","infrastructures"],["Trimble","construction"]],
 kpi:[["Croissance à changes constants","objectif 2026 : +14 à +15 %","objectif abaissé"]],
 dep:"Construction", next:"CA du 3e trimestre"},
MONC:{why:"Marque de luxe de la doudoune, très rentable, forte en Asie.",
 wrong:"La croissance reste sous 3 % (marque qui s'essouffle).",
 comp:[["Canada Goose","moins rentable"],["Grandes maisons de luxe","LVMH, Prada"]],
 kpi:[["Croissance à changes constants","+3 % (2025)","< 3 %"]],
 dep:"Doudounes ; Chine", next:"CA du 3e trimestre"},
RHM:{why:"Munitions et blindés : capacité de production rare au moment où l'Europe réarme.",
 wrong:"Les budgets de défense se retournent ou les retards d'exécution s'accumulent.",
 comp:[["BAE Systems","Royaume-Uni"],["KNDS","franco-allemand, non coté"],["Thales","électronique"]],
 kpi:[["Croissance du CA","objectif 2026 : +40 à +45 %","objectif abaissé"],["Conversion du cash","> 40 % annoncée","< 40 %"]],
 dep:"Commandes publiques", next:"CA du 3e trimestre"},
ATCO:{why:"Leader mondial des compresseurs et du vide, avec un après-vente récurrent.",
 wrong:"Les commandes reculent 4 trimestres de suite.",
 comp:[["Ingersoll Rand","États-Unis"],["Kaeser","non coté"]],
 kpi:[["Commandes organiques","+4 % (T4 2025)","recul 4 trimestres de suite"]],
 dep:"Industrie, semi-conducteurs (vide)", next:"Résultats trimestriels"},
DG:{why:"Concessions (autoroutes, aéroports) et construction : revenus indexés sur l'inflation.",
 wrong:"Fin des concessions françaises sans relais de croissance.",
 comp:[["Eiffage","concessions et BTP"],["Ferrovial","Espagne"]],
 kpi:[["Croissance organique","+2,6 % (2025)","< 2 %"]],
 dep:"Autoroutes françaises (fin vers 2030-2036)", next:"CA du 3e trimestre"},
};
